# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1328, 766)

        #importantfortheframetransparency
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_container = QtWidgets.QWidget(self.centralwidget)
        self.frame_container.setObjectName("frame_container")
        self.CurvyFrame1 = QtWidgets.QLabel(self.frame_container)
        self.CurvyFrame1.setGeometry(QtCore.QRect(80, 40, 1140, 641))
        self.CurvyFrame1.setStyleSheet("border-image: url(:/assets/images/assets/images/background.jpg);\n"
"border-radius: 20px;")
        self.CurvyFrame1.setText("")
        self.CurvyFrame1.setObjectName("CurvyFrame1")
        self.CurvyFrame2 = QtWidgets.QLabel(self.frame_container)
        self.CurvyFrame2.setGeometry(QtCore.QRect(100, 60, 1101, 591))
        self.CurvyFrame2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0, stop:0 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;")
        self.CurvyFrame2.setText("")
        self.CurvyFrame2.setObjectName("CurvyFrame2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_container)
        self.layoutWidget.setGeometry(QtCore.QRect(900, 50, 299, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.header_close = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.header_close.setContentsMargins(0, 0, 0, 0)
        self.header_close.setSpacing(0)
        self.header_close.setObjectName("header_close")
        self.close = QtWidgets.QPushButton(self.layoutWidget)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setAutoFillBackground(False)
        self.close.setStyleSheet("background-color: transparent;")
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/assets/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setIconSize(QtCore.QSize(30, 30))
        self.close.setAutoExclusive(True)
        self.close.setObjectName("close")
        self.header_close.addWidget(self.close, 0, QtCore.Qt.AlignRight)
        self.poweredBy = QtWidgets.QLabel(self.frame_container)
        self.poweredBy.setGeometry(QtCore.QRect(1040, 630, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.poweredBy.setFont(font)
        self.poweredBy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.poweredBy.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.poweredBy.setStyleSheet("color: rgb(255, 255, 255);")
        self.poweredBy.setScaledContents(False)
        self.poweredBy.setOpenExternalLinks(True)
        self.poweredBy.setObjectName("poweredBy")
        self.logincontainer = QtWidgets.QWidget(self.frame_container)
        self.logincontainer.setGeometry(QtCore.QRect(800, 260, 321, 311))
        self.logincontainer.setObjectName("logincontainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logincontainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_frame = QtWidgets.QFrame(self.logincontainer)
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.checkBox = QtWidgets.QCheckBox(self.login_frame)
        self.checkBox.setGeometry(QtCore.QRect(20, 150, 201, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"    border: 2px solid #4CAF50;  /* forbox */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: white; /* forText */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4CAF50; /* Background color when checkbox is checked */\n"
"    border: 2px solid #F2961F; /* Ensure the border remains visible when checked */\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.ResetButton = QtWidgets.QPushButton(self.login_frame)
        self.ResetButton.setGeometry(QtCore.QRect(240, 240, 61, 20))
        self.ResetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ResetButton.setDefault(False)
        self.ResetButton.setObjectName("ResetButton")
        self.ForgotPassword = QtWidgets.QLabel(self.login_frame)
        self.ForgotPassword.setGeometry(QtCore.QRect(120, 240, 121, 21))
        self.ForgotPassword.setStyleSheet("position: absolute;\n"
"width: 88px;\n"
"height: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 15px;\n"
"line-height: 17px;\n"
"\n"
"color: #FFFFFF;")
        self.ForgotPassword.setObjectName("ForgotPassword")
        self.SignInButton = QtWidgets.QPushButton(self.login_frame)
        self.SignInButton.setGeometry(QtCore.QRect(170, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SignInButton.setFont(font)
        self.SignInButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignInButton.setStyleSheet("\n"
"QPushButton#SignInButton { \n"
"border-radius: 3px;\n"
"height: 44px;\n"
"background-color: rgb(76, 175, 80);\n"
"color: rgb(255, 255, 255);\n"
"width: 64px;\n"
"}\n"
"QPushButton#SignInButton:hover {\n"
" background-color: rgb(200, 200, 200);\n"
"}")
        self.SignInButton.setObjectName("SignInButton")
        self.Login = QtWidgets.QLineEdit(self.login_frame)
        self.Login.setGeometry(QtCore.QRect(20, 40, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Login.setFont(font)
        self.Login.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #4CAF50;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"/* text */\n"
"position: absolute;\n"
"width: 88px;\n"
"height: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 15px;\n"
"line-height: 17px;\n"
"\n"
"\n"
"")
        self.Login.setText("")
        self.Login.setPlaceholderText("Email Address")
        self.Login.setObjectName("Login")
        self.RegisterButton = QtWidgets.QPushButton(self.login_frame)
        self.RegisterButton.setGeometry(QtCore.QRect(20, 240, 61, 21))
        self.RegisterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RegisterButton.setObjectName("RegisterButton")
        self.password_edit = QtWidgets.QLineEdit(self.login_frame)
        self.password_edit.setGeometry(QtCore.QRect(20, 90, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("border: none;\n"
"border-bottom: 2px solid #4CAF50;\n"
"background-color: transparent;\n"
"\n"
"/* text */\n"
"position: absolute;\n"
"width: 88px;\n"
"height: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 15px;\n"
"line-height: 17px;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.verticalLayout.addWidget(self.login_frame)
        self.SkillsTV = QtWidgets.QLabel(self.frame_container)
        self.SkillsTV.setGeometry(QtCore.QRect(190, 200, 301, 61))
        self.SkillsTV.setStyleSheet("font-size:42px;\n"
"gridline-color: qlineargradient(spread:pad, x1:0.687409, y1:0.647, x2:1, y2:0, stop:0.1875 rgba(134, 176, 13, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.SkillsTV.setObjectName("SkillsTV")
        self.TexttBody = QtWidgets.QLabel(self.frame_container)
        self.TexttBody.setGeometry(QtCore.QRect(190, 260, 491, 101))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(14)
        font.setUnderline(False)
        self.TexttBody.setFont(font)
        self.TexttBody.setStyleSheet("color: rgb(255, 255, 255);")
        self.TexttBody.setObjectName("TexttBody")
        self.movie_contaner = QtWidgets.QWidget(self.frame_container)
        self.movie_contaner.setGeometry(QtCore.QRect(190, 420, 561, 111))
        self.movie_contaner.setObjectName("movie_contaner")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.movie_contaner)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.movie_1 = QtWidgets.QFrame(self.movie_contaner)
        self.movie_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.movie_1.setStyleSheet("QFrame#movie_1 { \n"
"border-radius: 3px;\n"
"border-image: url(:/assets/images/assets/images/3.jpeg);\n"
"\n"
"}\n"
"QFrame#movie_1:hover {\n"
" background-color: rgb(200, 200, 200);\n"
"}")
        self.movie_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.movie_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.movie_1.setObjectName("movie_1")
        self.horizontalLayout_4.addWidget(self.movie_1)
        self.movie_2 = QtWidgets.QFrame(self.movie_contaner)
        self.movie_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.movie_2.setStyleSheet("QFrame#movie_2 { \n"
"border-radius: 3px;\n"
"border-image: url(:/assets/images/assets/images/1.jpeg);\n"
"\n"
"}\n"
"QFrame#movie_2:hover {\n"
" background-color: rgb(200, 200, 200);\n"
"}")
        self.movie_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.movie_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.movie_2.setObjectName("movie_2")
        self.horizontalLayout_4.addWidget(self.movie_2)
        self.movie_3 = QtWidgets.QFrame(self.movie_contaner)
        self.movie_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.movie_3.setStyleSheet("QFrame#movie_3 { \n"
"border-radius: 3px;\n"
"border-image: url(:/assets/images/assets/images/6.jpg);\n"
"}\n"
"QFrame#movie_3:hover {\n"
" background-color: rgb(200, 200, 200);\n"
"}")
        self.movie_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.movie_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.movie_3.setObjectName("movie_3")
        self.horizontalLayout_4.addWidget(self.movie_3)
        self.gridLayout.addWidget(self.frame_container, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        #--imp
        self.CurvyFrame1.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234, 221, 186, 100)))
        self.CurvyFrame2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105, 118, 132, 100)))
        self.SignInButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105, 118, 132, 100)))
        #---

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.poweredBy.setText(_translate("MainWindow", "Powered by QichinoLTD"))
        self.checkBox.setText(_translate("MainWindow", "Keep me logged in"))
        self.ResetButton.setToolTip(_translate("MainWindow", "Reset"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.ForgotPassword.setText(_translate("MainWindow", "Forgot Password?"))
        self.SignInButton.setToolTip(_translate("MainWindow", "Login"))
        self.SignInButton.setText(_translate("MainWindow", "Sign In"))
        self.RegisterButton.setToolTip(_translate("MainWindow", "Register"))
        self.RegisterButton.setText(_translate("MainWindow", "Register"))
        self.password_edit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.SkillsTV.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4caf50;\">🆂🅺🅸🅻🅻🆂🆃🆅</span></p></body></html>"))
        self.TexttBody.setText(_translate("MainWindow", "Watch thousands of Live Television Channels, Movies and\n"
"Series wherever you are on an ever-expanding list of\n"
"platforms including Windows or iOS devices Join Free\n"
"For One Month and Cancel anytime"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
